### ISSUE TITLE
你好。想问下关于在码云上部署出错的问题。

### ISSUE THREAD

**Issue by woniuxia** [jaywcjlove/rdoc#10]
http://yumenawei.gitee.io/blog/
码云平台的pages后面会带上一个目录。
但是rdoc的js文件是跟在网址的后面的，
求解怎么设置下。谢啦

**Comment by jaywcjlove** [comment]
@woniuxia 啊，你这个不是在跟目录下，我这个工具要升一下级呢。
默认所有资源都是根目录下读取资源`/`，所以，你的资源都加载不到，

这个要等我版本升级，支持相对路径。

**Comment by woniuxia** [comment]
好的，麻烦啦。
建议加个配置项。

**Comment by jaywcjlove** [comment]
@woniuxia 更新 `rdoc@1.3.10` 支持相对路径部署

**Comment by woniuxia** [comment]
已解决。十分感谢。
