### ISSUE TITLE
Module not found: Can't resolve './indexLayout.less'

### ISSUE THREAD

**Issue by oeliok** [jaywcjlove/rdoc#12]
我的运行环境
inux 4.14.0-deepin2-amd64 #1 SMP PREEMPT Deepin 4.14.12-2 (2018-01-06) x86_64 GNU/Linux
node 9.8.0 

rdoc -d about

/usr/local/lib/node_modules/rdoc/theme/default/layout/IndexLayout.js
Module not found: Can't resolve './indexLayout.less' in '/usr/local/lib/node_modules/rdoc/theme/default/layout

npm start

Module not found: Can't resolve './indexLayout.less' in '/media/oeli/doc/node_modules/rdoc/theme/default/layout'

Html Webpack Plugin:
  TypeError: $export is not a function
  
  - index.html:1880 Object../node_modules/core-js/library/modules/es6.object.define-property.js
    [spiderdoc]/[rdoc]/theme/default/index.html:1880:1
  
  - index.html:639 __webpack_require__
    [spiderdoc]/[rdoc]/theme/default/index.html:639:30
  
  - index.html:49 fn
    [spiderdoc]/[rdoc]/theme/default/index.html:49:20
  
  - index.html:894 Object../node_modules/core-js/library/fn/object/define-property.js
    [spiderdoc]/[rdoc]/theme/default/index.html:894:1
  
  - index.html:639 __webpack_require__
    [spiderdoc]/[rdoc]/theme/default/index.html:639:30
  
  - index.html:49 fn
    [spiderdoc]/[rdoc]/theme/default/index.html:49:20
  
  - index.html:725 Object../node_modules/babel-runtime/core-js/object/define-property.js
    [spiderdoc]/[rdoc]/theme/default/index.html:725:27
  
  - index.html:639 __webpack_require__
    [spiderdoc]/[rdoc]/theme/default/index.html:639:30
  
  - index.html:49 fn
    [spiderdoc]/[rdoc]/theme/default/index.html:49:20
  
  - index.html:1462 Object../node_modules/core-js/library/modules/_object-dp.js
    [spiderdoc]/[rdoc]/theme/default/index.html:1462:21
  
  - From previous event:
  
  - index.js:110 Compiler.
    [spiderdoc]/[html-webpack-plugin]/index.js:110:8
  
  - Tapable.js:206 Compiler.applyPluginsAsyncSeries
    [spiderdoc]/[tapable]/lib/Tapable.js:206:13
  
  - Compiler.js:354 Compiler.emitAssets
    [spiderdoc]/[webpack]/lib/Compiler.js:354:8
  
  - Compiler.js:58 onCompiled
    [spiderdoc]/[webpack]/lib/Compiler.js:58:19
  
  - Compiler.js:510 applyPluginsAsync.err
    [spiderdoc]/[webpack]/lib/Compiler.js:510:14
  
  - Tapable.js:202 next
    [spiderdoc]/[tapable]/lib/Tapable.js:202:11
  
  - CachePlugin.js:78 Compiler.
    [spiderdoc]/[webpack]/lib/CachePlugin.js:78:5
  
  - Tapable.js:204 next
    [spiderdoc]/[tapable]/lib/Tapable.js:204:14
  
  - index.js:46 Compiler.compiler.plugin
    [spiderdoc]/[create-spare-webpack-plugin]/index.js:46:7
  
  - Tapable.js:206 Compiler.applyPluginsAsyncSeries
    [spiderdoc]/[tapable]/lib/Tapable.js:206:13
  
  - Compiler.js:507 compilation.seal.err
    [spiderdoc]/[webpack]/lib/Compiler.js:507:11
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [spiderdoc]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:677 applyPluginsAsync.err
    [spiderdoc]/[webpack]/lib/Compilation.js:677:19
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [spiderdoc]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:668 applyPluginsAsync.err
    [spiderdoc]/[webpack]/lib/Compilation.js:668:11
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [spiderdoc]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:663 applyPluginsAsync.err
    [spiderdoc]/[webpack]/lib/Compilation.js:663:10
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [spiderdoc]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:659 applyPluginsAsyncSeries
    [spiderdoc]/[webpack]/lib/Compilation.js:659:9

**Comment by jaywcjlove** [comment]
@oeliok 回头我弄个 `Deepin` 系统测试一下。

你可以尝试通过工具初始化一个项目项目。

```bash
npm install -g  rdoc

rdoc init my-doc

cd my-doc

npm run start
```

**Comment by leafrabbit** [comment]
Linux mint 也会报出同样的错误，是不是基于 Debian 的系统都会有这样的问题？

**Comment by jaywcjlove** [comment]
@leafrabbit 这个需要在linux里面测试

**Comment by leafrabbit** [comment]
我不太熟悉 React，目前公司用的是 Vue， 类似的错误在我们做 Vue 项目时也出现过，是因为 less 插件的问题导致的无法编译 less 文件。可以看看是不是 less 插件在两个平台上有差异。

**Comment by jaywcjlove** [comment]
@leafrabbit 好的，有空的时候我装个虚拟机测试一下。

**Comment by jaywcjlove** [comment]
@leafrabbit @oeliok  

尴尬的bug

`rdoc@1.3.11`

**Comment by oeliok** [comment]
@jaywcjlove 结果是什么？？

**Comment by jaywcjlove** [comment]
@oeliok 引入文件大小写问题，在windows上和Mac上都不报错...
