### ISSUE TITLE
编译运行报错

### ISSUE THREAD

**Issue by dangyyeo** [jaywcjlove/rdoc#14]
![image](https://user-images.githubusercontent.com/12290338/40897120-a803a0e4-67eb-11e8-9a7b-5e203386c69b.png)

"rdoc": "1.8.x"

**Comment by jaywcjlove** [comment]
@oangy 

```bash
cd my-project
npm install
npm update rdoc

# 更新到  rdoc@1.9.0
npm install rdoc@1.9.0
```

**Comment by dangyyeo** [comment]
好的，多谢。
