### ISSUE TITLE
解析出错

### ISSUE THREAD

**Issue by JackSparrow008** [jaywcjlove/rdoc#4]
运行 rdoc init my-project 时，程序为什么会解析我的本地文件？

**Comment by jaywcjlove** [comment]
@JackSparrow008 什么意思？ `rdoc init my-project` 是从模板目录里面拷贝目录，不知道你遇到了什么情况

**Comment by JackSparrow008** [comment]
哦哦，最后是一个 internal error 
![snip20180125_1](https://user-images.githubusercontent.com/23499831/35367810-52a12108-01bb-11e8-8b1c-9daede017d17.png)

**Comment by jaywcjlove** [comment]
这个工具跟Ruby的文档工具同名了，要注意哦

**Comment by JackSparrow008** [comment]
额，那咋办呢？

**Comment by jaywcjlove** [comment]
@JackSparrow008 设置指令别名，编辑 `vi ~/.zshrc` 或者 `vi .bash_profile` 下面添加

```bash
alias rd='/usr/local/lib/node_modules/rdoc/.bin/rdoc.js'
```

编辑生效

```bash
source ~/.zshrc
```

定义了 `rd` 的别名命令，通过别名来运行

```bash
rd  init my-project
```

**Comment by jaywcjlove** [comment]
@JackSparrow008 

```bash
npm install rdoc -g

# /usr/local/bin/rdoc -> /usr/local/lib/node_modules/rdoc/.bin/rdoc.js
# /usr/local/bin/rdoc-cli -> /usr/local/lib/node_modules/rdoc/.bin/rdoc.js
```

定义了个别名 `rdoc-cli`

默认情况下两个命令都可以使用，`rdoc` 和 `rdoc-cli`，如果你的有冲突可以尝试使用另外一个命令。
