### ISSUE TITLE
如何使用ssh发布到服务器上

### ISSUE THREAD

**Issue by qinaichen** [jaywcjlove/rdoc#6]
我怎么使用publish或deploy命令将生成的文件通过ssh发布到服务器上

**Comment by jaywcjlove** [comment]
@qinaichen `rdoc deploy` 推送到 `gh-pages` 分支或者你指定分支，如果是 `gh-pages` 分支，并且是 GitHub 平台，就会通过 `https://你的GitHub账号.github.io/你的仓库名称` 进行预览。

如果你要通过 ssh 发布，你可以通过 ssh 登录进入，克隆你的Git仓库，或者将生成的静态资源，拷贝到对应的静态资源目录中。

**Comment by jaywcjlove** [comment]
@qinaichen 你也可以通过，钩子去自动部署到你的服务器中。

你推送到指定的分支，钩子检测到 push  事件，去执行脚本更新你的网站....
