### ISSUE TITLE
不支持图片吗?

### ISSUE THREAD

**Issue by CurryHan** [jaywcjlove/rdoc#9]
看了下`.rdoc-dist`文件夹下 图片没有生成

**Comment by jaywcjlove** [comment]
@CurryHan 支持图片，不会又是因为windows 的问题吧

**Comment by jaywcjlove** [comment]
@CurryHan 图片引入比较特殊，你先看一下图片引入的文档，我检查一下，是不是windows的路径问题，Mac和 Linux 上是没有问题的。

https://react-doc.github.io/#/introduce/guides/insert-img

**Comment by jaywcjlove** [comment]
@CurryHan  我看了你生成后的代码，你的图片存放位置有问题，应该放到你指定的 Markdown 文档目录之中。

**Comment by jaywcjlove** [comment]
@CurryHan  windows我也测试了是没有问题的。

**Comment by CurryHan** [comment]
@jaywcjlove 抱歉 没看到文档上的图片说明

**Comment by CurryHan** [comment]
windows下测试了下 
用markdown语法插入图片 build的时候图片会成功生成.
而用html的方式则不能成功生成.

**Comment by jaywcjlove** [comment]
@CurryHan 这个我需要测试看一下什么问题。

**Comment by jaywcjlove** [comment]
@CurryHan 

https://react-doc.github.io/#/introduce/guides/insert-img

注意图片存储目录。

```html
<img src="https://avatars1.githubusercontent.com/u/1680273?s=460&v=4"/>
<img width="60" height="60" src="./assets/react-logo.svg"/>
```
